### ISSUE TITLE
ArgumentError: expect the argument to be a String, got NilClass (nil)

### ISSUE THREAD

**Issue by matsn0w** [mocyuto/fluent-plugin-raven#6]
Hey there,

I was testing your plugin today in my `fluent/fluentd:edge-debian` Docker container. With a simple HTTP input, I'm getting the following error:

```log
fluentd-fluentd-1  | 2023-02-02 14:35:38 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="expect the argument to be a String, got NilClass (nil)"
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/sentry-ruby-core-4.9.2/lib/sentry/utils/argument_checking_helper.rb:9:in `check_argument_type!'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/sentry-ruby-core-4.9.2/lib/sentry/hub.rb:109:in `capture_message'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/sentry-ruby-core-4.9.2/lib/sentry-ruby.rb:293:in `capture_message'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-raven-0.1.7/lib/fluent/plugin/out_raven.rb:51:in `block in write'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/event.rb:315:in `each'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/event.rb:315:in `block in each'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/event.rb:314:in `each'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-raven-0.1.7/lib/fluent/plugin/out_raven.rb:50:in `write'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1180:in `try_flush'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
fluentd-fluentd-1  |   2023-02-02 14:35:38 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
fluentd-fluentd-1  | 2023-02-02 14:35:38 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_85c/5f3b876d2e86579e6ad716da1ba8cf6d.log
```

This is my `fluent.conf`:

```conf
<source>
  @type http
  port 9000
  bind 0.0.0.0
</source>

<match **>
  @type raven
  dsn "#{ENV['SENTRY_DSN']}"
  <buffer>
    @type file
    path /var/log/fluent/buf
  </buffer>
</match>
```

The cURL request I use for testing:

```sh
curl -X POST -d 'json={"hey":"ho"}' http://localhost:9000
```

Am I doing something wrong or is this some kind of bug?

Thanks for any help in advance!
matsn0w

**Comment by matsn0w** [comment]
Update: I messed around a bit and figured out that it works when you manually specify `worker` and `message` in the JSON request...

That seems strange to me, or isn't it? I'm new to fluentd, so I might be missing something.

Working request:

```sh
curl -X POST -d 'json={"worker":0,"message":"ho"}' localhost:9000
```

**Comment by mocyuto** [comment]
Thank you for reporting.
I assumed that it catch only fluentd error, but your case doesn't need worker and message.
So, I will fix it for applying your case.

**Comment by mocyuto** [comment]
`message` value have to set to record, because sentry issue is identified by message.
So, no `message` record will filtered at v0.1.8.

You can try below command with v0.1.8, and could sent errors to sentry.
```
 curl -X POST -d 'json={"message":"ho"}' http://localhost:9000
```
